### ISSUE TITLE
重複投稿の対応について

### ISSUE THREAD

**Issue by koichrionishi** [dounokouno/TransmitMail#21]
dounokouno 様

お世話になっております。

重複投稿を防ぐ為cookieを利用して下記のような形で制限したいと考えているのですが、
勉強不足なためコードをどこに追加すれば、わかりません。

$date = date('Ymd');
setcookie($date,'true',time()+60*60*24*1);

// 投票済みの場合
if(isset($_COOKIE[$date])){
    $message = '投票済みです。';
}

すみませんが、ご教授いただけると嬉しいです。
また、他に良い方法がございましたら、教えていただけると嬉しいです。

何卒宜しくお願い申し上げます。

**Comment by dounokouno** [comment]
@koichrionishi 様

TransmitMailをご利用いただきありがとうございます。
また、お返事が遅くなってしまい申し訳ありません。

いくつか質問をさせてください。

# 1. TransmitMailのリロードによる重複送信防止機能について

重複送信を防ぐ簡易的な機能はTransmitMailにありますが、その機能は利用できず別の実装をしたい、という認識であっていますでしょうか？

認識があっている場合は、どのような実装をしたいか、簡単で構いませんので @koichrionishi 様の考えている仕様をご教示いただければと思います。

# 2. コードの意図について

「1」の質問にも関係しますが、ご提示いただいたのコードの意図がわからず、私自身が少々混乱しています。

特に `time()+606024*1` の部分の意図がよくわかりません。

いろいろ考えた結果、 @koichrionishi の考えられている重複送信防止の仕様は下記のような内容かなと想像をしています。

1. メール送信を送信した日は再度メールを送信することができない
2. 「1」の仕様はブラウザを閉じた後も継続する（ブラウザを閉じて開きなおしても同日の場合はメール送信できない）

上記の私の想像が正しい場合、`time()+606024*1` は `time()+60*60*24` が正しいコードかなと思っております。

参考にそれぞれの実行結果の違いをご紹介します。

## サンプルコード

```php
<?php
date_default_timezone_set('Asia/Tokyo');

var_dump(date('Y-m-d H:i:s', time()+606024*1));
var_dump(date('Y-m-d H:i:s', time()+60*60*24));
```

## 実行結果

```console
string(19) "2015-02-08 17:31:31"
string(19) "2015-02-02 17:11:07"
```

※本日の17:11頃に実行
※上記の実行結果から「7日と20分数十秒後を指定した理由はなんだろう…？」と混乱してしまいました…。

# 3. 重複送信防止のユーザビリティについて

「2」の私の想像する仕様が正しい場合、ユーザービリティ的に良くない動作が考えられます。

通常、TransmitMailを利用したメールフォームの場合、入力項目に「メールアドレス」があり、送信完了画面表示後に入力したメールアドレス宛に自動返信メールが届いていることを確認することで入力内容が正しいことを確認する、といった流れになるかと思います。

仮に「2」の仕様でメールフォームを作ってしまうと、自動返信メールが届かないなどによってメールアドレスの入力を間違っていたことに気がついた場合、日付が変わるまでメールフォームが利用できない、となってしまい、利用者にとってとても不便な状態になってしまうのではと考えております。

上記の懸念も考慮した上で行いたいカスタマイズであれば特に問題ありませんが、安易に重複送信を防止されたいと考えられている場合は、改めて仕様と利用者のことを考えてみていただければと思います。

十分考慮した上でカスタマイズを行いたい場合は、その旨、コメントいただけましたら、改めてカスタマイズについてのアドバイスをさせていただきます。

**Comment by dounokouno** [comment]
@koichrionishi 様

一旦、この issue は閉じさせていただきますね。
引き続きこの issue の件で不明点がありましたが、 issue を再度オープンしていただくか、別の issue を立てていただければと思います。
