### ISSUE TITLE
メールアドレスのmatch判定について

### ISSUE THREAD

**Issue by sbmegaman** [dounokouno/TransmitMail#22]
```php
if (!empty($_POST[$array[0]])
			&& !empty($_POST[$array[1]])
			&& $_POST[$array[0]] != $_POST[$array[1]]
			)
```

今現在こういった判定になっていますが、メールアドレスの入力が必須でない設定の時に
これだと片方が空欄で片方にだけメールアドレスを入れた時にバリデーションを通過していまっています。

```php
if (!empty($_POST[$array[0]])
-			&& !empty($_POST[$array[1]])
+			|| !empty($_POST[$array[1]])
			&& $_POST[$array[0]] != $_POST[$array[1]]
			)
```

こう変えたほうがよろしいと思うのですがいかがでしょうか。

**Comment by sbmegaman** [comment]
ありゃ、これだとマッチしててもバリデーション通過しませんね。
こうでした

```php
	if ( (!empty($_POST[$array[0]]) || !empty($_POST[$array[1]]) )
			&& $_POST[$array[0]] != $_POST[$array[1]]
			) 
```

**Comment by dounokouno** [comment]
@sbmegaman 様

ご指摘ありがとうございます。状況を確認し改めてお返事させていただきますね。
（現在、少々忙しくしているため。お返事が遅くなってしまったらすみません…。）

**Comment by dounokouno** [comment]
@sbmegaman 様

お返事がすっかり遅くなってしまい申しわけありませんm(_ _)m

ご指摘の不具合を確認しましたので、ご教示いただいたコードのように修正いたしました。
ご確認いただければ幸いです。

https://github.com/dounokouno/TransmitMail/blob/master/index.php#L294
