### ISSUE TITLE
7文字以上のgTLDによるメールアドレスの妥当性検証に失敗する

### ISSUE THREAD

**Issue by dominion525** [dounokouno/TransmitMail#24]
メールアドレスの検証に下記の正規表現が使われています。

```
function check_mail_address($s) {
	return preg_match('/^([a-z0-9_]|\-|\.|\+)+@(([a-z0-9_]|\-)+\.)+[a-z]{2,6}$/i', $s);
}
```
https://github.com/dounokouno/TransmitMail/blob/master/lib/common.php#L263

ところが現在では、6文字を超えるgTLDが実用されています。
参考:  http://www.iana.org/domains/root/db

このため、7文字以上のgTLDだと検証に失敗します。

そもそも「メールアドレス」(RFC5322) を示す正規表現は書けないことで有名であり、そもそもチェックはいらないのではないかという意見もありますが、妥協案としてのHTML5にて使用されているものを使うなどしてはどうでしょうか。
参考:  http://www.w3.org/TR/html5/forms.html#valid-e-mail-address

**Comment by dounokouno** [comment]
@dominion525 

> ところが現在では、6文字を超えるgTLDが実用されています。

上記件に関しましては、以前に別の方からも指摘を受けていまして、修正を予定していますが、まだ手がつけられていない状態です…。

https://github.com/dounokouno/TransmitMail/issues/3#issuecomment-58453615

> そもそも「メールアドレス」(RFC5322) を示す正規表現は書けないことで有名であり、そもそもチェックはいらないのではないかという意見もあります

はい、存じております。

> 妥協案としてのHTML5にて使用されているものを使うなどしてはどうでしょうか。

ご提案ありがとうございます！「HTML5で使用されている」はわかりやすい指標で良いですね。ご提案の内容で近日中に修正します。修正が完了しましたらメンションでお知らせしますね。

**Comment by dounokouno** [comment]
@dominion525 

ご指摘いただいた件の修正を行いました。

また、修正内容をまとめた issue を別途立てましたので、この issue は close させていただきますね。

https://github.com/dounokouno/TransmitMail/issues/25
