### ISSUE TITLE
雑談掲示板

### ISSUE THREAD

**Issue by dounokouno** [dounokouno/TransmitMail#3]
雑談にご利用ください。

# 2020年12月10日追記

GitHub で Discussions 機能が使えるようになったので、雑談掲示板は Discussions の方をご利用ください 🙇‍♂️ → discussions #70

**Comment by ryohei0411** [comment]
とても長い間、変わらずに更新を行い続ける
姿勢に感銘を受けました😂
いつもありがとうございます😌

**Comment by Randing** [comment]
@dounokouno 様

いつも有難うございます。

YAML初心者として一つお願いなのですが

■YAML 記法についての補足　のところに
タブ文字を使ってはならない　と記載いただけませんでしょうか。

bccの宛先を増やしたくて、設定ファイルに追記を増やした時に、
行頭になにげなくタブを入れていたせいで、
設定ファイルが途中から壊れていたようで、
しばらくあたふたしました。

もしかしたら、同様の初心者の方がいるかと思い…
ご検討お願いいたします。

**Comment by dounokouno** [comment]
@Randing 様

ご指摘ありがとうございます。追記しました。

https://github.com/dounokouno/TransmitMail/wiki/設定ファイルの記述方法（v2）

**Comment by Randing** [comment]
早速ありがとうございました！

**Comment by Randing** [comment]
動作環境(PHP)の報告です。
transmit2は、PHP 7.2.13 (CGI版) で無事動作しております。
--
最近WordPressのphp5系のサポートが終了したため、このタイミングで
レンタルサーバーのPHPをバージョンアップしました。
実は管理しているサイトでtransmit旧版が動作しなくなり、この度アップグレードしました。

**Comment by Randing** [comment]
「さくらのレンタルサーバ スタンダード」です。（元コメントにも付記します）
書いたつもりで、お手間をすみません！よろしくお願い致します。

**Comment by dounokouno** [comment]
GitHub で Discussions 機能が使えるようになったので、雑談掲示板は Discussions の方をご利用ください 🙇‍♂️ → discussions #70
