### ISSUE TITLE
エラー時のメール送信先について

### ISSUE THREAD

**Issue by ryosuke0803** [dounokouno/TransmitMail#35]
よろしくお願いいたします。
まだ理解不足でもうしわけありませんが、質問させていただきます。

なにかしらのエラーが起きた際、
特にどこに飛ばすなどは設定していないのですが、
現状エラーメッセージがアパッチのサーバーに飛びます。
自動返信などの設定をしていますが、それはアパッチのサーバーには設定しておりません。

こちらを違う場所に変更したいのですが、可能でしょうか？

**Comment by dounokouno** [comment]
@ryosuke0803 様

何らかのエラーが発生した場合、 Apache にエラーログが出力されるのは正しい仕様のように思います。

> こちらを違う場所に変更したいのですが、可能でしょうか？

具体的にはどこにログを出力されたいでしょうか？

**Comment by ryosuke0803** [comment]
お返事ありがとうございます。

お客様のサーバーでのことで、ちょっと詳しく確認できていないのですが、
アパッチのサーバーに？メールで届いているようで、こちらをお客様自身にメールを飛ばしたいのです。

**Comment by dounokouno** [comment]
@ryosuke0803 様

> アパッチのサーバーに？メールで届いているようで

どのようなメールが Apache に届いているかはわかりますでしょうか？わかっている場合、差し支えない範囲でメールの内容を貼り付けていただけましたら、調査の助けになるかもしれません。

**Comment by ryosuke0803** [comment]
少々お待ちください！

**Comment by dounokouno** [comment]
一旦、本issueはcloseさせていただきます。まだ解決されていないようでしたら、本issueにコメントいただくか、新しくissueを作成してください。
