### ISSUE TITLE
スパムメール

### ISSUE THREAD

**Issue by yksnowchi** [dounokouno/TransmitMail#38]
大量のスパムメールが1分ごとに届きました。TransmitMailではスパム対策の設定はしていますか？画像認証の追加可能ですか？もしなければ他の対策案はありますか？

**Comment by dounokouno** [comment]
「セッションによる多重送信防止機能」がスパム対策にもなり得ると考えていましたが、それを超えてスパムメールがきている、ということですよね...。

TransmitMail でのスパム対策は、事後的な対策になりますが、アクセス拒否ホスト設定で送信元の IP アドレスを拒否していただく形になります。

https://github.com/dounokouno/TransmitMail/wiki/設定ファイルの記述方法（v2）#アクセス拒否ホスト設定

ただ、スパムメール毎に IP アドレスが違う場合は、対策にならないので、他の方法を検討いただく必要があります。

画像認証の追加に関しましては、簡単ではないかと思いますが、追加すること自体はできる想定です。（TransmitMail に CAPTCHA を追加した、というブログ記事を読んだ記憶があるのですが、どのブログ記事だったかは失念してしまいました...。）ただ、私が実際に追加したことがないので、ここでご説明することができません...。

時期はお約束できませんが、 TransmitMail に CAPTCHA を追加する件はブログ記事か何かに書いてまとめたいと思います。

**Comment by yksnowchi** [comment]
遅くなりました、ご回答ありがとうございます。
あれから、Google reCAPTCHAを入れて様子をみてたのですが、スパムメールが毎分ごとに来て止まりません。今、Transmitmail v1.5.7を使用しています。脆弱性という点で、関係しますか？

**Comment by dounokouno** [comment]
@yksnowchi 様

TransmitMail v1.5.7 は脆弱性が含まれるバージョンですので、バージョンアップをおすすめいたします。

http://dounokouno.com/2015/04/20/transmitmail-の脆弱性について/

ただ、この脆弱性はスパムメールとは関係はありません。

CAPTCHA も超えてきているということは、もしかすると手動でスパムメールを送っているのかもしれませんね...。仮にそうだとすると、スパムメールなのか通常のお問い合わせメールなのかを判断することが難しいように思います...。

送信元の IP アドレスはやはり毎回違いますか？

**Comment by yksnowchi** [comment]
>送信元の IP アドレスはやはり毎回違いますか？

確認したところ、続けて同じのもあれば、違うのもあり、１つ限定するのがむずかしいです。

**Comment by dounokouno** [comment]
@yksnowchi 様

そうなんですね...。そうしますと、対応が難しそうです...。

現在はそういった機能はありませんが、同一IPアドレスからの連続送信を抑制する機能、のようなものがあってもいいかもしれませんね。（IPアドレスが変わる場合があるようですので、これだけでもあまり意味はないかもしれませんが...。）今後の機能追加にて検討させていただきます。

**Comment by dounokouno** [comment]
一旦、本issueはcloseさせていただきます。
