### ISSUE TITLE
送信メールに入力内容が表示されない

### ISSUE THREAD

**Issue by orange1109** [dounokouno/TransmitMail#40]
dounokouno様
いつもお世話になっております。

送信メールに入力内容が表示されません。
以前ご質問された方の回答やよくある質問に記載されている内容を試してみたのですがうまくいきませんでした。
送信メールを見てみると文頭に「？」がついているのでエンコードの問題かと思うのですが…。
お忙しいところ大変恐縮ですが、ご返信いただけると幸いです。
よろしくお願いいたします。

◎環境情報
サーバ：さくらインターネット
PHPバージョン：PHP7.1

◎こちら参考にさせていただきました
https://github.com/dounokouno/TransmitMail/issues/13
https://github.com/dounokouno/TransmitMail/wiki/%E3%82%88%E3%81%8F%E3%81%82%E3%82%8B%E3%81%94%E8%B3%AA%E5%95%8F

**Comment by dounokouno** [comment]
@orange1109 様

TransmitMailをご利用いただきありがとうございます。

私の契約しているさくらのレンタルサーバーのPHP 7.1では特に問題なくメール送信でき、文字化けは確認できませんでした。

以下の項目に関しまして、ご確認をお願いいたします。

- 送信メールに入力内容が表示されないとのことですが、メールのテンプレートの内容は問題なく表示されていますでしょうか？（テンプレート部分は問題なく表示されていて、入力内容だけが文字化けしていますか？もしくは、テンプレートの内容も文字化けしていますか？）

また、メールの件名が長すぎる場合に、本文内に件名の一部が入り込む（？）といった現象が発生するようですので、件名が長い場合は短くした状態で送信テストをしてみていただいて、症状が再現するかご確認いただければ幸いです。

**Comment by orange1109** [comment]
@dounokouno様
早速のご返信ありがとうございます。
伝わりにくい質問の仕方で申し訳ございません。補足いたします。

★mail_body.txt（一部抜粋）
お名前={$姓.value}{$名.value}
フリガナ={$セイ.value}{$メイ.value}
会社名={$会社名.value}

★受信メール内容
?お問い合わせフォームよりメールが送信されました。
お名前　=　
フリガナ　=　
会社名　=　

>送信メールに入力内容が表示されないとのことですが、メールのテンプレートの内容は問題なく表示されていますでしょうか？（テンプレート部分は問題なく表示されていて、入力内容だけが文字化けしていますか？もしくは、テンプレートの内容も文字化けしていますか？）

メールのテンプレートの内容は問題なく表示されております。入力内容のみが「空白」になります。

>件名が長い場合は短くした状態で送信テストをしてみていただいて、症状が再現するかご確認いただければ幸いです。

件名は15文字程度なので問題ないかと思われます。
以上、よろしくお願いいたします。

**Comment by dounokouno** [comment]
@orange1109 様

引き続き下記点のご確認をお願いいたします。

- 入力エラー画面、入力確認画面では入力内容は問題なく表示されていますでしょうか？
- 自動返信メールの方は入力内容が問題なく表示されていますでしょうか？
- phpinfo等で `mbstring.internal_encoding` の値が何になっているかご確認をお願いいたします。
- TransmitMailの初期状態のmail_body.txtを使っても「?お問い合わせフォームよりメールが送信されました。」と表示されるか、一度、ご確認をお願いいたします。

**Comment by orange1109** [comment]
@dounokouno様
いつも大変お世話になっております。
>入力エラー画面、入力確認画面では入力内容は問題なく表示されていますでしょうか？

こちら問題なく表示されております。

>自動返信メールの方は入力内容が問題なく表示されていますでしょうか？

やってみたのですが自動返信メールが受信されませんでした。
こちら参考にしました。https://github.com/dounokouno/TransmitMail/wiki/%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%81%AE%E8%A8%98%E8%BF%B0%E6%96%B9%E6%B3%95

>phpinfo等で mbstring.internal_encoding の値が何になっているかご確認をお願いいたします。

UTF-8でした。

>TransmitMailの初期状態のmail_body.txtを使っても「?お問い合わせフォームよりメールが送信されました。」と表示されるか、一度、ご確認をお願いいたします。

「？」は表示されませんでした。下記が内容になります。
お問い合わせフォームよりメールが送信されました。
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IP: XXXXXXXXXX
HOST: XXXXXXXXXX
USER_AGENT: XXXXXXXXXX
XXXXXXXXXX
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

補足になりますがチェックモードを確認したところ、パーミッションでNGが出ておりました。
log/: NG (705)
tmp/: NG (705)
さくらインターネットから、パーミッションを「705」に変更したのですがNGのままです。
こちらも何か関係していますでしょうか。

何度も申し訳ございません。
お忙しいところ大変恐縮ではございますが、ご対応よろしくお願いいたします。

**Comment by dounokouno** [comment]
@orange1109 様

コメントありがとうございます。

引き続きで申し訳ありませんが、下記点のご確認をお願いいたします。

> 補足になりますがチェックモードを確認したところ、パーミッションでNGが出ておりました。
> さくらインターネットから、パーミッションを「705」に変更したのですがNGのままです。

正しいパーミッションは「707」になりますので、そのようにご設定をお願いいたします。

上記のようにパーミッションを変更いただいて、logディレクトリに何かエラーログは出力されていないか、ご確認をお願いいたします。

また、設定ファイルにて `display_error` を `true` に設定して動作検証を行っていただき、画面にエラーが出力されるか、ご確認をお願いいたします。

- TransmitMailを設置いただいているディレクトリや上層のディレクトリで、何か別のアプリケーションを動かしていたりしますでしょうか？
- TransmitMailを設置いただいているディレクトリや上層のディレクトリで、.htaccessやphp.iniなどでPHPの設定を変更されていたりしますでしょうか？
- TransmitMailの初期状態のファイル一式で、設定ファイルの `to_email` だけご自身のメールアドレスに変更いただき、入力内容が正しく出力されるか、一度、ご確認をお願いいたします。

**Comment by orange1109** [comment]
@dounokouno 様
度々失礼いたします。毎度のことながら大変お世話になっております。

>正しいパーミッションは「707」になりますので、そのようにご設定をお願いいたします。

チェックモードがすべてOKになりました。ありがとうございました。

>上記のようにパーミッションを変更いただいて、logディレクトリに何かエラーログは出力されていないか、ご確認をお願いいたします。

特にエラーは出ませんでした。

>TransmitMailを設置いただいているディレクトリや上層のディレクトリで、何か別のアプリケーションを動かしていたりしますでしょうか？

ほかのアプリケーションは存在しております。全て必要なファイルなので削除などは出来ません…。

>TransmitMailを設置いただいているディレクトリや上層のディレクトリで、.htaccessやphp.iniなどでPHPの設定を変更されていたりしますでしょうか？

上記にある変更はしておりません。

>TransmitMailの初期状態のファイル一式で、設定ファイルの to_email だけご自身のメールアドレスに変更いただき、入力内容が正しく出力されるか、一度、ご確認をお願いいたします。

入力内容が正しく出力されていることを確認いたしました。
また個別出力の書き方でも問題なく表示されました。
尚、初期状態のファイル一式で変更したのは「input.html」「confirm.html」「mail_box.txt」です。
HTMLファイルで読み込んでいるjsなどが原因になっているのでしょうか？

恐縮なのですが、私自身原因の特定が出来ていないので
ご返信いただけますと幸いです。どうぞよろしくお願いいたします。

**Comment by dounokouno** [comment]
@orange1109 様

コメントありがとうございます。

> ほかのアプリケーションは存在しております。

上記件、了解いたしました。

> 全て必要なファイルなので削除などは出来ません…。

他のアプリケーションの影響が考えられるかと思い伺っただけですので、削除などはしなくて大丈夫ですよ😄 

また、「TransmitMailの初期状態のファイル一式」で問題ないということは、  @orange1109 が作成、編集されたどれかのファイルの書き方が間違っている、または何か悪さをしている可能性が高いように思っています。（もしくは、 @orange1109 様のおっしゃるようにJavaScriptが影響している可能性も考えられます。）

よろしければ私の方で内容を確認しますので、関連しそうなファイル一式を下記メールアドレス宛にお送りいただくことは可能でしょうか？

dounokouno@gmail.com

ご検討をお願いいたします。

**Comment by dounokouno** [comment]
ファイル一式をお送りいただき、内容を精査したところ、メール本文に入力内容が出力されない件は、 `{$hiddens}` の記述がないことが原因でした。 `{$hiddens}` の記述については下記辺りを参照。

https://github.com/dounokouno/TransmitMail/blob/master/confirm.html#L38

送信メールの先頭に「?」が表示される件は、テキストエディタで見ることができず、消すことができない何かが残ってしまっているようでした。

以上で本件は解決しましたので、closeします。
