### ISSUE TITLE
拒否設定について

### ISSUE THREAD

**Issue by yuuteimiyaoukimukou** [dounokouno/TransmitMail#41]
はじめまして、お世話になります。
フリーメールを使用できないよう拒否する事が出来るでしょうか。

**Comment by dounokouno** [comment]
@yuuteimiyaoukimukou 様

上記件は TransmitMail の基本機能にはありません。

TransmitMail をカスタマイズすることで特定のドメインのメールアドレス（ gmail.com など）はメールを送ることができない、といった仕様にはできるかと思います。

ただ、どのドメインを送信不可にするか、の仕様策定は気を使わないといけないかもしれません。無料で利用できるメールアドレスは無数にあるかと思いますので。全ての無料で利用できるメールアドレスを送信不可にする、といった仕様は現実的ではないように思います。

**Comment by yuuteimiyaoukimukou** [comment]
ご回答ありがとうございます。
こちらでアドレスのリストを用意しております。
*@gmail.com,*@yahoo.co.jp,*@outlook.comなどを記述していく方法ではいかがでしょうか。

**Comment by dounokouno** [comment]
@yuuteimiyaoukimukou 様

アドレスのリストをご用意されているとのことですので、そのリストにあるドメインのメールアドレスを送信不可にすることはカスタマイズで対応可能です。

**Comment by yuuteimiyaoukimukou** [comment]
なるほど、ありがとうございます。
それで、カスタマイズはどうやれば良いのでしょうか。

**Comment by dounokouno** [comment]
@yuuteimiyaoukimukou 様

PHP がお分かりになるようでしたら、下記記事を参考にメールアドレスのバリデーションを追加いただく形になるかと思います。

https://qiita.com/dounokouno/items/4014dee5bdb2b8c7d1e1

PHP がお分かりにならないようでしたら、カスタマイズは難しいかもしれません...。

**Comment by yuuteimiyaoukimukou** [comment]
ありがとうございます、やってみます。

**Comment by dounokouno** [comment]
一旦、本issueはcloseさせていただきます。まだ解決されていないようでしたら、本issueにコメントいただくか、新しくissueを作成してください。
