### ISSUE TITLE
確認画面でinput内容を連結したい

### ISSUE THREAD

**Issue by ogata9816** [dounokouno/TransmitMail#44]
電話番号を「市外局番」「市内局番」「下四桁」の3つのinputに分けて入力する様にし、出力は連結した状態で表示したいです。

inputを電話番号1・電話番号2..と分けて書くと、「電話番号1（2or3）が未入力です」と表示され、且つ確認画面ではそれぞれの入力結果が改行されて出てしまいますが、希望としましては、inputで分けてもrequiredはまとめて「電話番号が未入力です」とし、確認画面でそれぞれが改行せずに一行に出て欲しいです。
どの様にすれば希望のように出力されるかご教授頂ければ幸いです。

**Comment by dounokouno** [comment]
@ogata9816 様

> 電話番号を「市外局番」「市内局番」「下四桁」の3つのinputに分けて入力する様にし、出力は連結した状態で表示したいです。

上記件は個別出力機能をご利用いただくことで実現できるかと思います。個別出力機能のテンプレートファイルの書き方に関しましては、下記ファイルをご参照いただければと思います。

https://github.com/dounokouno/TransmitMail/blob/master/confirm_kobetsu.html

エラーの出力に関しましては、 TransmitMail には現時点ではそのような機能はありませんので、 TransmitMail をカスタマイズしていただくか、 JavaScript でバリデーションを実装していただく形になるかと思います。

**Comment by dounokouno** [comment]
本 issue は一旦、 close させていただきます。もしまだ未解決でしたら、再度、本 issue を open していただくか、別の issue を作成してください。
