### ISSUE TITLE
自動返信メールにおいてヘッダー情報の一部が本文エリアに表示される

### ISSUE THREAD

**Issue by nyamiell** [dounokouno/TransmitMail#45]
あるサイトに設置したお問い合わせフォームの自動返信メールにおいて、
メールアドレス欄に特定のドメインのアドレスを入力し自動返信メールを受信した場合のみ
ヘッダー情報の一部が、本文エリアの最初に表示されてしまいます。

具体的には以下の内容です。
---ここから---
send-by MailFunction
Date: Wed, 10 Oct 2018 10:00:45 +0900 (JST)
---ここまで---
※メールヘッダーの一部が本文の最上部に2行ほど表示されてしまいます。

複数のメールアドレス（ドメイン・メールサーバの異なる）で試しましたが、
表示されるのは、特定のドメインのもののみです。

どのような理由が考えられるでしょうか？
こちらから他にお伝えすべき内容あればご教示いただけるとありがたいです。
（初めての質問で、投稿場所が適切でなかったら申し訳ありません。）

**Comment by dounokouno** [comment]
@nyamiell 

投稿場所はこちらで問題ありません 😃 

いくつか確認をさせていただきたいことがありますので、下記点のご確認をお願いいたします。（それぞれ調査および情報提供可能な範囲で問題ありません。）

- ご利用のTransmitMailのバージョンはいくつでしょうか？
- TransmitMailを動作させているPHPのバージョンはいくつでしょうか？
- TransmitMailを設置されたサーバーはレンタルサーバーでしょうか？レンタルサーバーでしたら、レンタルサーバーの会社名やプラン名をご教示ください。
- 症状が発生するメールアドレスはレンタルサーバーのものでしょうか？レンタルサーバーのものでしたら、レンタルサーバーの会社名やプラン名をご教示ください。（またはG Suiteのようなサービスを利用されていますでしょうか？）

**Comment by nyamiell** [comment]
ご返信ありがとうございます。

確認したところ、PHPのバージョンが動作環境外（5.3.3）でした。。。

PHPのバージョン変更を行った上で、こちらで再度確認してみます。
事前確認不足でお手数おかけしました。

-----------------------------
・利用中のTransmitMailのバージョン　2.1.0
・TransmitMailを動作させているPHPのバージョン　5.3.3
・TransmitMailを設置したサーバ・プランなど　現時点で不明
・症状が発生するメールアドレス　さくらインターネット　レギュラープラン　Gmail経由で受信
-----------------------------

**Comment by dounokouno** [comment]
本 issue は一旦、 close させていただきます。もしまだ未解決でしたら、再度、本 issue を open していただくか、別の issue を作成してください。
