### ISSUE TITLE
サンクスページのURLを変更したい

### ISSUE THREAD

**Issue by teruringo** [dounokouno/TransmitMail#46]
finish.htmlで作成したページのURLが変更をしたいのですが、
それは可能でしょうか。

いまは擬似的にjavaScriptで
```
  <script>
    history.replaceState("","","thanks.php");
    ga("set", "page", "thanks.php");
    ga("send", "pageview");
  </script>
```

のように書き換えています。

**Comment by teruringo** [comment]
蛇足ながら、gtag.jsの場合は
```
    history.replaceState("", "", "thanks.php");
    gtag("config", "UA-128632737-1");

```
ですかね。

**Comment by dounokouno** [comment]
@teruringo 様

Googleアナリティクスで完了ページを計測したい、ということでしたら、コメントいただいたようにGoogleアナリティクスの `page` を変更していただくのが良いかと思います。（私の場合はそうしています。）

参考: https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications?hl=ja

どうしてもリダイレクトが必要、ということでしたら、 TransmitMail の本体にカスタマイズを加える場合、 lib/TransmitMail.php の 1027 行目あたりで完了ページの表示を行なっておりますので、この部分を PHP でリダイレクトするように書き換えていただくことで実現できるかと思います。

https://github.com/dounokouno/TransmitMail/blob/master/lib/TransmitMail.php#L1027

ご参考になれば幸いです。

**Comment by dounokouno** [comment]
今思い出しましたが、Googleアナリティクスで完了ページを計測したい、ということでしたら、confirm.html の完了ページへ post する form 要素の action 属性の値の末尾に `?finish` などのパラメータをつけることでGoogleアナリティクスで完了ページを計測することが可能です。

```html
<form method="post" action="index.php?finish">
```

ご参考になれば幸いです。

**Comment by dounokouno** [comment]
本 issue は一旦、 close させていただきます。もしまだ未解決でしたら、再度、本 issue を open していただくか、別の issue を作成してください。

**Comment by teruringo** [comment]
@dounokouno 様

大変すみません！
見逃してました！ありがとうございました！！！
