### ISSUE TITLE
送信メールの内容の先頭に？マークが付く

### ISSUE THREAD

**Issue by taka224** [dounokouno/TransmitMail#47]
相手側に自動返信で送られるメールと自分宛に送信されるメールに関してですが、本文の先頭に？マークが付くのですが、どのような原因が考えられますか？

お手数ですが、よろしくお願いします。

**Comment by dounokouno** [comment]
@aka224 様

いくつか確認をさせていただきたいことがありますので、下記点のご確認をお願いいたします。（それぞれ調査および情報提供可能な範囲で問題ありません。）

- ご利用のTransmitMailのバージョンはいくつでしょうか？
- TransmitMailを動作させているPHPのバージョンはいくつでしょうか？
- TransmitMailを設置されたサーバーはレンタルサーバーでしょうか？レンタルサーバーでしたら、レンタルサーバーの会社名やプラン名をご教示ください。
- 症状が発生するメールアドレスはレンタルサーバーのものでしょうか？レンタルサーバーのものでしたら、レンタルサーバーの会社名やプラン名をご教示ください。（またはG Suiteのようなサービスを利用されていますでしょうか？）
- 症状を確認されたメーラーは何でしょうか？（PC向けアプリ、スマホ向けアプリ、ブラウザでGmailを閲覧、など）
- Twitterの方にも書きましたが、送信メールの件名が長い場合にそのような症状が発生した記憶がありますので、送信メールを短くしてみていただいて、症状が再現するか、ご確認をお願いいたします。 https://twitter.com/dounokouno/status/1061956815850618880
- TransmitMailの最新バージョンをそのまま設置いただいて、症状が再現するか、ご確認をお願いいたします。

**Comment by dounokouno** [comment]
本 issue は一旦、 close させていただきます。もしまだ未解決でしたら、再度、本 issue を open していただくか、別の issue を作成してください。
