### ISSUE TITLE
確認画面から入力画面に戻るとtextareaの入力内容のみ消えている

### ISSUE THREAD

**Issue by trans-tookoo** [dounokouno/TransmitMail#49]
いつも利用させていただいています。

確認画面から入力画面に戻ると、電話番号やメールアドレス等の内容は残っているのですが、textareaに書き込んだ内容のみ消えてしまいます。たくさん書いて読み返した際、書き直したい場合もあると思うので、内容が消えないようにしたいのですが、方法はありますでしょうか。

**Comment by dounokouno** [comment]
@trans-tookoo 様

textarea に入力内容を挿入する記述はされていますでしょうか？詳しい記述方法はデフォルトのテンプレートファイルを参照いただければと思います。

https://github.com/dounokouno/TransmitMail/blob/master/input.html#L57

上記をご確認いただいても解決しない場合は、入力画面（ input.html ）の textarea の前後の HTML をこの issue にコメントいただければと思います。

**Comment by dounokouno** [comment]
本 issue は一旦、 close させていただきます。もしまだ未解決でしたら、再度、本 issue を open していただくか、別の issue を作成してください。
