### ISSUE TITLE
サブジェクトを入力させたい

### ISSUE THREAD

**Issue by toshioq** [dounokouno/TransmitMail#50]
大変有用なフォームのソリューションをありがとうございます。
すごく便利なのですが、入力項目でサブジェクトを入力させることは可能でしょうか？
config.ymlでのサブジェクト指定で入力項目を指定できればいけそうに思えますが、方法はありませんでしょうか？

**Comment by dounokouno** [comment]
@toshioq 様

下記の私の書いた Qiita の記事が参考になるかと思います。

https://qiita.com/dounokouno/items/c1b3d8a043560e785ce8

**Comment by toshioq** [comment]
なるほどー
これは参考になります。
ありがとうございます。

**Comment by dounokouno** [comment]
本 issue は一旦、 close させていただきます。もしまだ未解決でしたら、再度、本 issue を open していただくか、別の issue を作成してください。
