### ISSUE TITLE
Facebook Pixel Code設置について

### ISSUE THREAD

**Issue by Ksuzuki2019** [dounokouno/TransmitMail#51]
いつも利用させていただいております。
ありがとうございます。

TransmitMailにFacebook Pixel Codeを設置したいのですが、
https://www.facebook.com/business/m/pixel-set-up-step-2
コードを入れると真っ白になってしまいます。
{if:$required.---}などのタグとうまくいかないようです。。
何かいい方法ありますでしょうか？

お忙しいところ恐縮です。
どうぞよろしくお願いいたします。

**Comment by dounokouno** [comment]
@Ksuzuki2019 

どのようなコードをどこに書かれているか、修正された箇所、 Facebook Pixel Cod を挿入された箇所を可能な範囲でコメントいただけるとありがたいですmm

**Comment by Ksuzuki2019** [comment]
ご返信ありがとうございます。

コードは＜/haed＞の上に入れ、内容は以下のようなものになります。

`
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '000000000000000');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=000000000000000&ev=PageView&noscript=1"
/></noscript>
`

コードを入れないと問題なく表示、送受信できますが、
このコードを入れるとページ自体が真っ白になってしまい、
ソースを見ると

`
<script>
  !function(f,b,e,v,n,t,s)`

まであり、途中ソースが消えてて、
フォーム後半から出ています。


試しに、必須部分の
`{if:$required.日}`
等のソースを消すと表示されます。

分かりずらい説明で申し訳ございません。
何か良い方法ありますでしょうか？
よろしくお願いいたします。

**Comment by dounokouno** [comment]
@Ksuzuki2019 

なんとなく理解できてきました。

Facebook Pixel Code のコードの `{if` あたりが TransmitMail のテンプレートエンジンの文法として認識されてしまっているようです。

Facebook Pixel Code のコードを少し改変してよければ、例えば下記のように改行を入れることで改善されるのではと考えています。改行を加えても Facebook Pixel Code の動作には影響はない想定です。

```
<script>
!function(f,b,e,v,n,t,s) {
    if(f.fbq)return;n=f.fbq=function(){
        n.callMethod? n.callMethod.apply(n,arguments):n.queue.push(arguments)
    };
    if(!f._fbq)f._fbq=n;
    n.push=n;
    n.loaded=!0;
    n.version='2.0';
    n.queue=[];
    t=b.createElement(e);
    t.async=!0;
    t.src=v;
    s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)
}
(window, document,'script', 'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '000000000000000');
fbq('track', 'PageView');
</script>
```

ここまで丁寧に改行しなくても、初めの方に登場する `{if` を `{ if` のように半角スペースを入れるだけでも解決するかもしれません。（ここに半角スペースを入れても JavaScript の動作としては何も変わらないです。）

ご確認いただければ幸いです。

**Comment by Ksuzuki2019** [comment]
問題なく表示されました！！
{ if　半角スペースを入れただけで大丈夫でした。

大変助かりました！
お忙しいところご対応いただき感謝いたします。
ありがとうございました。
