### ISSUE TITLE
ヘッダー共通化、CSRF設定、画像送信が共存できない。

### ISSUE THREAD

**Issue by udonka** [dounokouno/TransmitMail#54]
TransmitMailを初めて利用させていただいています。

他のページとのパーツ共通化をしたく、また、CSRFの設定もしたかったため、
https://github.com/dounokouno/TransmitMail/issues/2#issuecomment-493384884
製作者さんのこちらのレスを参考に、 new TransmitMail() をファイル冒頭に、 runをhtmlの中に入れてみました。
その結果、 run の中でもheaderの送信を行なっているようで、PHPのエラーが出ていました。
その結果、添付画像へのリクエスト 「/index.php?file=file_16394797675d639b843c580_3-2.png」 ができなくなり、表示できなくなりました。

現状、ヘッダー共通化、CSRF設定、画像送信　を共存させる方法はありませんでしょうか？

**Comment by udonka** [comment]
とりあえず、 index.php の代わりに image.php というものをつくり、こちらではHTMLを一切出力させないようにし、添付画像表示専用としました。 内容も requireとnew とrunのみにしました。そしたら動きました。

**Comment by dounokouno** [comment]
@udonka 様

TransmitMail のバージョンはいくつをご利用でしょうか？2019年8月6日にリリースした v2.4.0 でヘッダー出力周りの修正を行い、添付画像へのリクエスト時に不要なヘッダーを出力しないように修正を行いました。一度、ご利用のバージョンをご確認いただき、ご利用のバージョンが v2.4.0 以下をご利用の場合は v2.4.0 を試してみていただければ幸いです。

v2.4.0 から index.php の書き方も少し変わりまして、その件は下記にまとめておりますので、あわせてご確認いただければ幸いです。

https://github.com/dounokouno/TransmitMail/issues/26#issuecomment-518464581

**Comment by udonka** [comment]
@dounokouno 様

ご丁寧にご返信ありがとうございます！
たしかに、 2.3を使っておりました。
2.4を試してみたいと思います！

ありがとうございました。
