### ISSUE TITLE
送信時、エラーでも通る時がある。

### ISSUE THREAD

**Issue by ts-mori** [dounokouno/TransmitMail#62]
dounokouno 様
いつもお世話になっております。

バグかもしれないのですが、明らかなミスでもバリデートが通ったり、
エラー表示が出たりしています。
```
<dt class="contactKoumoku">電話番号<span class="requir">必須</span>{if:$required.電話番号}
  <span class="error" id="telError">電話番号が正しいかご確認ください。</span>
  {/if:$required.電話番号}<span class="error">{if:$len.電話番号}
    {$len.電話番号}
    {/if:$len.電話番号} </span></dt>
<dd class="contactInputWrapper">
  <input class="contactInput" id="tel" type="tel" name="電話番号" value="{$電話番号}" placeholder="0123456789" />
  <input type="hidden" name="num_hyphen[]" value="電話番号" />
  <input type="hidden" name="len[]" value="電話番号 10-11">
</dd>
<dt class="contactKoumoku">メールアドレス<span class="requir">必須</span>{if:$required.メールアドレス}
  <span class="error">{$required.メールアドレス}</span>
  {/if:$required.メールアドレス}</dt>
<dd class="contactInputWrapper">
  <input class="contactInput" type="email" name="メールアドレス" value="{$メールアドレス}" />
  <input type="hidden" name="required[]" value="メールアドレス">
  <input type="hidden" name="email[]" value="メールアドレス">
  {if:$email.メールアドレス}
  {$email.メールアドレス}
  {/if:$email.メールアドレス}
</dd>
```
ソースが悪ければ、ご指摘いただけないでしょうか？

他に、jsで電話番号のハイフォンを削除しています。
電話番号でも、何もしていない、mailでも明らかなミスでも通る時があり、
jsとの相性なのかもわかりかねます。

どうぞよろしくお願いいたします。

**Comment by dounokouno** [comment]
@ts-mori 

入力画面のテンプレートが上記のようになっていて、どの項目にどのような入力をしたときに、バリデーションが通ったり、エラーが表示されたりしますか？どの項目にどのような入力をして、どのような結果を期待して、どのような期待と違う結果になったか、をご教示いただけるとありがたいですmm

**Comment by ts-mori** [comment]
dounokouno 様
お世話になっております。
検証、ありがとうございます。

電話番号を「0900000」でエラーの時と確認画面に進むときがあります。
メールでは「a」　　　　でエラーの時と確認画面に進むときがあります。
メールでは「a@a.」　　 でエラーの時と確認画面に進むときがあります。

同じ入力をしていても、エラーになるとき（多い）と、通るときがあります。
PCもスマホでも同じように発生します。

どうぞよろしくお願いいたします。

**Comment by dounokouno** [comment]
@ts-mori 様

お返事ありがとうございます。

コメントいただいた HTML の記述をして、ローカル開発環境で動作検証を行ってみましたが、私の環境ではご報告のような状況は発生しませんでした。

私が確認した環境は下記の通りです。

- OS: macOS 10.15
- ブラウザ: Safari 13
- サーバー: PHP のビルトインウェブサーバー
- PHP のバージョン: 7.4.2

@ts-mori 様が確認されている環境を詳しく教えていただきたいです。教えていただきたい情報は例えば下記の情報です。

- OS 名とそのバージョン
- ブラウザ名とそのバージョン
- レンタルサーバーを利用されている場合は、会社名とプラン名など
- PHP のバージョン

テンプレートの書き方は問題なさそうに見えますので、 JavaScript が何か予期しない動きをしているのかもしれません。利用されている JavaScript の、ライブラリであればその名前とバージョンと、独自で記述しているものがあれば、可能な範囲で貼り付けていただけるとありがたいですmm

**Comment by ts-mori** [comment]
dounokouno 様
大変お世話になっております。
動作検証をいただきありがとうございます。

- ■windows10 pro バージョン1809■PHP Version： 5.3.3
- ■ブラウザ：
- IE11.1039.17763.0
- Google Chrome
- バージョン: 79.0.3945.130（Official Build） （64 ビット）
- firefox73.0.1
- サーバー
- NTT PCコミュニケーションズ
- WebARENA SuitePRO V4（サーバータイプ32G）

昨日はメールもおかしかったのですが、今日は再現できませんでした。
電話番号は、間違えた番号を入力後全消しや1文字程度入れただけでも通ったりします。


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

$(function() {
  $("#tel").blur(function() {
    var tel = $("#tel").val().replace(/[━.*‐.*―.*－.*\-.*ー.*\-]/gi, '');
    //↑ 入力値のハイフォンなどを削除
    tel = tel.replace(/[０-９]/g, function(s) {
      //↑ 全角数字だったら半角に変更
      return String.fromCharCode(s.charCodeAt(0) - 0xFEE0);
    });
      $(this).val(tel);
  });
});

**Comment by ts-mori** [comment]
dounokouno 様
大変お世話になっております。環境は以下です。

- OS：windows10 pro バージョン1809
- ブラウザ：IE11.1039.17763.0/Google Chromeバージョン: 79.0.3945.130（Official Build）（64 ビット）/firefox73.0.1
- サーバー：NTT PCコミュニケーションズWebARENA SuitePRO V4（サーバータイプ32G）
- PHP Version： 5.3.3

昨日はメールもおかしかったのですが、今日は再現できませんでした。
電話番号は、間違えた番号を入力後検証後全消しや1文字程度入れるなどをすると、通りやすいようです。

--jsの情報
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

```
$(function() {
  $("#tel").blur(function() {
    var tel = $("#tel").val().replace(/[━.*‐.*―.*－.*\-.*ー.*\-]/gi, '');
    //↑ 入力値のハイフォンなどを削除
    tel = tel.replace(/[０-９]/g, function(s) {
      //↑ 全角数字だったら半角に変更
      return String.fromCharCode(s.charCodeAt(0) - 0xFEE0);
    });
      $(this).val(tel);
  });
});
```
どうぞよろしくお願いいたします。

**Comment by dounokouno** [comment]
@ts-mori 様

コメントありがとうございます。

PHP のバージョンが「5.3.3」とのことですが、 TransmitMail は PHP 5.6 以上で動作確認を行なっています。 TransmitMail では PHP 5.3 ではサポートされていない関数などを利用していますので、そのままでは想定通り動作しないと思われます。設定ファイルで `display_error: true` とするとエラーが表示されるかと思います。

**Comment by ts-mori** [comment]
dounokouno 様
大変お世話になっております。

config.ymlに「display_error: true」を追加してみましたが、状況は変わらずです。
サポート対象外でしょうか？

よろしくお願いします。

**Comment by dounokouno** [comment]
@ts-mori 様

設定ファイルで `display_error: true` を設定しても、エラーメッセージなどが表示されなかった、ということでしょうか？とすると、エラー表示に関しても、 PHP 5.3 では動作しないのかもしれないですね。。

**Comment by ts-mori** [comment]
dounokouno 様
大変お世話になっております。

PHP 5.3では、難しいのですね。とりあえず、jsでバリデーションしておきます。
PHPのバージョンアップも検討してみます。

ありがとうございました。
又何かありましたら、よろしくお願いします。
