### ISSUE TITLE
メールが送れない

### ISSUE THREAD

**Issue by ts-mori** [dounokouno/TransmitMail#63]
dounokouno 様

いつも利用させていただいています。
今回、初めてエラーページになってしまいました。

入力画面→確認画面には進むのですが、エラーページに行ってしまいます。
エラーコードは、
Notice: Undefined offset: 0 in /xxx/transmitMail/lib/qdmail.php on line 1933
Notice: Undefined offset: 0 in /xxx/transmitMail/lib/qdmail.php on line 1933
となっております。

phpは全く分からず、対応方法がわかりません。
ご教示いただけないでしょうか？

どうぞよろしくお願いいたします。

**Comment by dounokouno** [comment]
@ts-mori 様のご利用状況に関して、いくつか確認をさせてください。

- PHP のバージョンはいくつでしょうか？
- TransmitMail はどこかのレンタルサーバーに設置されたものでしょうか？可能でしたら、レンタルサーバーの会社名とプラン名をご教示いただけるとありがたいです。（解決のヒントになるかもしれないので。）
- TransmitMail のバージョンはいくつでしょうか？
- TransmitMail のチェックモードで何かエラーが出ていないでしょうか？
    - https://github.com/dounokouno/TransmitMail/wiki/%E8%A8%AD%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E8%A8%98%E8%BF%B0%E6%96%B9%E6%B3%95%EF%BC%88v2%EF%BC%89#%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%83%A2%E3%83%BC%E3%83%89%E3%81%AE%E5%88%A9%E7%94%A8
- 確認画面から完了画面に進もうとしたときに、エラーページが表示される、といった状況であっていますでしょうか？
- 設定ファイル（ config/config.yml でしょうか？）でどのような設定をされているか、可能な範囲で構いませんので、ご教示いただけると助かりますmm

**Comment by ts-mori** [comment]
dounokouno 様
情報は以下です。
•サーバー：NTT PCコミュニケーションズWebARENA SuitePRO V4（サーバータイプ32G）
•PHP Version： 5.3.3
チェックモード
システム情報
    システム名: TransmitMail バージョン: 2.4.1
sendmail
    /usr/sbin/sendmail -t -i
セーフモード
    Off
htmlなどはすべてOK
---------
config.yml
config:
   email: mori@ts.net
    subject: らぼ♡ご予約
    auto_reply_subject: ［らぼ♡］ご予約ありがとうございます
    auto_reply_name: らぼ♡
    auto_reply_email_input_name: メールアドレス
    auto_reply_from_email: t-s@ts.net
    checkmode: 2

どうぞよろしくお願いいたします。

**Comment by dounokouno** [comment]
@ts-mori 様

ご利用状況のコメントありがとうございます。

以前、下記でもコメントさせていただきましたが、TransmitMail は PHP 5.6 以上で動作確認を行なっています。 TransmitMail では PHP 5.3 ではサポートされていない関数などを利用していますので、そのままでは想定通り動作しないと思われます。

https://github.com/dounokouno/TransmitMail/issues/62#issuecomment-592829050

**Comment by ts-mori** [comment]
dounokouno 様
お調べいただきありがとうございます。

PHPがバージョン外なのは、承知していますが、兄弟ディレクトリでは動いているので、
エラーなどを元に何とかならないかと、お尋ねしました。

TransmitMailでも、php5.3で動くバージョンがあれば、ご教示いただけますと
幸甚でございます。
お忙しいところ、恐縮ですが、どうぞよろしくお願いいたします。

**Comment by dounokouno** [comment]
> PHPがバージョン外なのは、承知していますが、兄弟ディレクトリでは動いているので、

そうなんですね。

エラーメッセージを拝見しますと、エラーは下記の行で発生しているようで、

https://github.com/dounokouno/TransmitMail/blob/master/lib/qdmail.php#L1933

ざっとコードを読むと、メールアドレス部分で発生しているようです。

自動返信メールを利用されているようですが、自動返信メールのメールアドレス入力欄は `<input type="text" name="メールアドレス">` になっていて、そちらにメールアドレスの入力はされていますでしょうか？

参考: https://github.com/dounokouno/TransmitMail/wiki/設定ファイルの記述方法（v2）#自動返信メールの宛先

> TransmitMailでも、php5.3で動くバージョンがあれば、ご教示いただけますと幸甚でございます。

TransmitMail は結構昔のバージョンで PHP 5.3 のサポートを止めましたので、いつのバージョンまで PHP 5.3 が使えていたかは失念してしまいました。コミットログを探していただければ PHP 5.3 のサポートを止めたタイミングが見つかるかもしれません。もしくは、 PHP 5.3 でエラーになる箇所を、 PHP 5.3 で動くように TransmitMai のプログラムを修正いただくことでも対応可能かと存じます。

**Comment by ts-mori** [comment]
dounokouno 様
ご教示ありがとうございます。
<input type="text" name="メールアドレス">まわりを念入りに見ましたが、問題が無いように思えました。
念のため、動いている兄弟の同じ場所のソースを貼り付けましたところ、メールの送信が可能になりました。

つまり、タイプミス？　解決です。
いつもながらに、素早いレスポンスと、ヒントをいただきありがとうございました。

また、何かありましたらよろしくお願いいたします。

**Comment by dounokouno** [comment]
@ts-mori 様

上記件、了解しました。

> 念のため、動いている兄弟の同じ場所のソースを貼り付けましたところ、メールの送信が可能になりました。

上記は config.yml ファイルでしょうか？ lib ディレクトリ以下のファイルでしょうか？

config.yml でしたら、不正な文字列が入っていたりしたかもですね。下記などでチェックいただくと何かエラーが見つかるかもしれません。ご参考までに。

https://codebeautify.org/yaml-validator

**Comment by ts-mori** [comment]
>> 念のため、動いている兄弟の同じ場所のソースを貼り付けましたところ、メールの送信が可能になりました。
>上記は config.yml ファイルでしょうか？ lib ディレクトリ以下のファイルでしょうか？
input.html内のメールアドレス回りです。

目視では、全くわかりませんでしたが、メールアドレス回りとの情報で、
念のためコピペしたら、送信できるようになりました。

ありがとうございました！！
