### ISSUE TITLE
確認画面に移らない

### ISSUE THREAD

**Issue by taka224** [dounokouno/TransmitMail#78]
多重送信防止を無効にすると、確認画面に移りますが多重送信防止は有効の方が良いですよね？
何か原因で確認画面に移らないでしょうか？
エラーは特に出ていません。

**Comment by dounokouno** [comment]
> 多重送信防止を無効にすると、確認画面に移りますが多重送信防止は有効の方が良いですよね？

有効にした方が良いか否か、に関しましては、
どちらでも良いと思います。

名前の通り「多重送信」を「防止」する機能で、
あくまで便利機能なので、機能を無効にしてもそれほど大きく困ることはないと思われます。

商品購入や何かの申し込みフォームとして TransmitMail を利用される場合は、「多重送信防止機能」を有効にされた方が良いと思います。

> 何か原因で確認画面に移らないでしょうか？

多重送信防止機能を有効にされたり無効にされたりしたあとで、確認画面に遷移しない問題が発生した、ということでしょうか？

**Comment by taka224** [comment]
ありがとうございます。

> 多重送信防止機能を有効にされたり無効にされたりしたあとで、確認画面に遷移しない問題が発生した、ということでしょうか？
はい、そうですね！
有効だと確認画面に行かなかったので、無効にしたら動きました。
有効のままでも確認画面に移るようにしたいです。

**Comment by taka224** [comment]
エラーが出ていました。

Warning:  session_start(): Session cannot be started after headers have already been sent in <b>/home/inco-g/www/wp/contact/lib/TransmitMail.php on line 372

Warning:  session_regenerate_id(): Session ID cannot be regenerated when there is no active session in <b>/home/inco-g/www/wp/contact/lib/TransmitMail.php on line 375

**Comment by dounokouno** [comment]
> > また、もしレンタルサーバーを利用されている場合、 PHP と Session に何か制限などはかけられていたりしないでしょうか？
>
> わかりません。レンタルサーバーはさくらサーバーです。

「さくらサーバー」というのはさくらのレンタルサーバーのことでしょうか？さくらのレンタルサーバーのヘルプページなどに情報がのっていないかご確認をお願いしたいです。

> エラーが出ていました。

エラーを拝見しますと、 WordPress を設置しているディレクトリと同じディレクトリに TransmitMail を設置されようとしている、といった状況でしょうか？

**Comment by taka224** [comment]
できました。
独自のheader,phpをindex.phpの先頭に読み込んでいたんですが、後の方に変えたら確認画面に移りました。

**Comment by dounokouno** [comment]
@taka224 

そうなんですね、了解です。

では、本 issue は解決した、ということで良いでしょうか？

**Comment by taka224** [comment]
はい、大丈夫です。

**Comment by dounokouno** [comment]
であれば、解決した旨のコメントと、 Close with comment ボタンで issue を close にしてもらえると助かります。
