### ISSUE TITLE
さくらサーバーで動かない

### ISSUE THREAD

**Issue by taka224** [dounokouno/TransmitMail#79]
さくらサーバーにサンプルファイルをアップしても表示しません。

**Comment by taka224** [comment]
申し訳ありません。
動きました。

**Comment by dounokouno** [comment]
@taka224 

動作したようで安心いたしました。

どういった状況で動作せず、どういった状況では動作したか、今後、同じような問題に遭遇するかもしれない方のために簡単で構いませんので、情報を整理してコメントしていただけると助かります。

**Comment by taka224** [comment]
TransmitMail.phpをアップしてなかっただけでした。
申し訳ありませんでした。
