### ISSUE TITLE
Fatal error: Call to a member function set() on a non-object in /xxx/TransmitMail/lib/TransmitMail.php on line 415

### ISSUE THREAD

**Issue by kanai-ini** [dounokouno/TransmitMail#81]
お世話になっております。初めてご質問させていただきます。

使用させていただいておりますモジュールにおいて、セキュリティアップデートを適用させたく、
v2.0.8→最新版へとlib内部のソースを一括で上書きしたところ、
1つのサーバでは
https:では問題なく動作し、
http:では件名のエラーが発生してしまいました。
また、別のサーバではhttps:、http:どちらも同様のエラーが発生してしまっています。

原因がわからずにいるのですが、何か考えられる理由などありましたらご教授いただきたく存じます。

お手数をおかけしますが、何卒よろしくお願いいたします。

**Comment by dounokouno** [comment]
@kanai-ini 様

エラーを拝見しますと、おそらく `index.php` の変更が適用されていないのではと思われます。詳しくは一度、 `index.php` の差分をご確認いただければと思います。

https://github.com/dounokouno/TransmitMail/blob/master/index.php

またバージョンアップの際はお手数ですが「全ての php ファイル」を更新していただくようお願いいたします。その際に、独自に php ファイルに修正を加えられている場合は、適宜、修正箇所のマージをお願いいたします。

**Comment by kanai-ini** [comment]
@dounokouno 様
大変お手数をおかけしております。ご返信ありがとうございます。

index.phpの更新実施してみましたが、現状変わらずでした。。

以下のファイルをマージしたのですが、他に更新すべきファイルはありますでしょうか？
・index.php（フォーム本体）
・config/config.yml（設定用YAML）
・TransmitMail/lib 以下のファイル一式

何卒よろしくお願いいたします。

**Comment by dounokouno** [comment]
@kanai-ini 様

アップデートのご対応ありがとうございます。

「 https: では問題なく動作」し、「 http: では件名のエラーが発生」したとのことですが、利用されているサーバーでは http と https で配置ディレクトリが異なったりはしないでしょうか？または http も https も同じ配置ディレクトリでしょうか？

もし配置ディレクトリが異なる場合は、 https 側はアップデートできており、 http 側がアップデートされていない、といった状況が考えられるかもと思い確認させていただきました。

ご確認をお願いいたします。

**Comment by kanai-ini** [comment]
@dounokouno 様

お手数をおかけしております。ご確認いただきありがとうございます。

おっしゃる通り、httpsとhttpで見る先が異なっていました。。ありがとうございます。
そして本来のエラーを確認できたのですが、こちらのサーバのPHPバージョンが5.3.29と古く、それによってエラーが発生しているようでした。

PHPバージョンアップをする方向で考えているのですが、念の為、現バージョンでセキュリティアップデートの対応をする方法があるか確認させていただけますでしょうか？もし他に手法があればで構いません。

大変お手数をおかけし申し訳ありません。よろしくお願いいたします。

**Comment by dounokouno** [comment]
@kanai-ini 様

> PHPバージョンアップをする方向で考えているのですが、念の為、現バージョンでセキュリティアップデートの対応をする方法があるか確認させていただけますでしょうか？もし他に手法があればで構いません。

TransmitMail では一部の PHP の文法で PHP v5.3 では動作しない文法を利用しています。ですので、対応方法としましては、セキュリティアップデートを適用後、 PHP v5.3 でエラーになっている箇所を修正していただくことで対応可能かと思います。どの行が PHP v5.3 に未対応だったかは失念してしまいましたが、無名関数を利用している箇所だった記憶があるので、 `lib/TransmitMail.php` であれば下記の行を無銘関数を利用しないコードに修正いただくことで PHP v5.3 でも動作する気がします。

https://github.com/dounokouno/TransmitMail/blob/master/lib/TransmitMail.php#L1292

が、もしかすると他にも PHP v5.3 でエラーになる箇所があるかもしれないので、エラーを確認いただきながらエラーがなくなるまでエラーを修正する、といった対応になるかと思います。

**Comment by kanai-ini** [comment]
@dounokouno 様

ご返信いただきありがとうございます。v5.3用に修正する手法について承知いたしました。
バージョンアップグレードするか、修正するか、方針決めて対応したいと思います。

この度はこちら側の問題でお手数をおかけし申し訳ありませんでした。とても助かりました。
こちらのissueはクローズさせていただきますね。

何卒よろしくお願いいたします。
