### ISSUE TITLE
Googleスプレッドシートとの連携について

### ISSUE THREAD

**Issue by evoworx-nakata** [dounokouno/TransmitMail#84]
dounokouno様

お世話になっております。
一点質問させてください。

現在、以下の記事を参考にGoogleスプレッドシートとの連携を行なっていまして、
特にエラー等の問題なく最後の工程まで進めたのですが、お問い合わせフォームから送信をしてもスプレッドシートに入力した情報が反映されません。

お問い合わせフォーム側でエラーが出ていないところをみると、Google Cloud Platform側との連携が上手くできていないのかなと思い、記事のキャプチャと現状のGoogle Clound Platformの該当箇所を見比べていくと、クライアントIDおよびメールアドレスの形式が異なるようなのですが、こちらのクライアントIDは21の数字からなるもので、メールアドレスは末尾が`.iam.gserviceaccount.com`からなるものでそれぞれ合っていますでしょうか？

TransmitMailというよりは、スプレッドシートとの連携の話がメインになってしまい申し訳ありません。
よろしくお願いいたします。

※記事の「スプレッドシートに権限を追加する」の箇所ではこのメールアドレスを、「設定情報を config.yml に追加する」の「google_client_id: {クライアント ID}」「google_client_email: {メールアドレス}」にもそれぞれこのクライアントIDとメールアドレスを設定しています。

https://qiita.com/dounokouno/items/01561521e1f9d4cd49b3

**Comment by dounokouno** [comment]
@evoworx-nakata 様

Google Cloud Platform の画面を改めてみてみたのですが、私が Qiita で記事を書いたときからいろいろ画面などが変わっているみたいですね。。

だいぶ仕様が変わっているようですので、私の Qiita 記事は参考にならなさそうなので、下記記事などを参考に、私の Qiita 記事は参考にせずに新しく実装していただいた方が良いかも知れません。

【PHP】Google spreadsheet API（V4）の使い方・全25実例！ – console dot log
https://blog.capilano-fw.com/?p=4337

**Comment by evoworx-nakata** [comment]
> @evoworx-nakata 様
> 
> Google Cloud Platform の画面を改めてみてみたのですが、私が Qiita で記事を書いたときからいろいろ画面などが変わっているみたいですね。。
> 
> だいぶ仕様が変わっているようですので、私の Qiita 記事は参考にならなさそうなので、下記記事などを参考に、私の Qiita 記事は参考にせずに新しく実装していただいた方が良いかも知れません。
> 
> 【PHP】Google spreadsheet API（V4）の使い方・全25実例！ – console dot log https://blog.capilano-fw.com/?p=4337

dounokouno様

ご返信ありがとうございます。
参考記事も教えていただきありがとうございます。

こちらですが、Google Cloud Platformは使わず別の方法でスプレッドシートと連携を行うことにしました。
質問しておいて申し訳ありません。
またTransmitMailの件で何かあった際には、よろしくお願い致します。

**Comment by dounokouno** [comment]
上記件、了解しました 👍
