### ISSUE TITLE
添付ファイルの添付時にエラーが起こります

### ISSUE THREAD

**Issue by GensIto** [dounokouno/TransmitMail#85]
テンプレート通りに書いているのですが添付後に送信ボタンを押すと確認画面に進まず、添付ファイルのアップロードに失敗しました。とメッセージがでで動かないです。
php 7.4 セーフモードoff 添付ファイルの指定もしておりサイズもmax以下でアップロードしているのですが他に考えられる問題はなんでしょうか?

**Comment by dounokouno** [comment]
添付ファイルを一時保存するディレクトリのパーミッションは正しく設定されていますでしょうか？チェックモードなのでご確認いただければ幸いです。

**Comment by GensIto** [comment]
こちらディレクトリを全て元通りにして事故解決いたしました。
お手数おかけしました。ありがとうございました！
