### ISSUE TITLE
添付ファイルの画像確認

### ISSUE THREAD

**Issue by GensIto** [dounokouno/TransmitMail#87]
添付ファイルが確認画面でも表示されません
pdfファイル時の時はサムネイルのようなものは表示されないのでしょうか?

**Comment by dounokouno** [comment]
@GensIto 様

> pdfファイル時の時はサムネイルのようなものは表示されないのでしょうか?

一般的なブラウザには PDF ファイルを HTML に埋め込んでサムネイルで表示するような機能がないため（私が知る限りでは）、 JavaScript のプラグインなどを利用しないと表示することはできないと思います。

ググってみたところ、下記の記事が見つかりました。ご参考になれば幸いです。

[HTMLでPDFを表示する方法5選！PDFの埋め込みをするには？ | Aprico](https://aprico-media.com/posts/4051)

**Comment by GensIto** [comment]
ご回答ありがとうございます!!!!
そーなのですね。記事まで検索していただきありがとうございます読んで解決します。
