### ISSUE TITLE
phpバージョンアップによるCSRFトークンエラーについて

### ISSUE THREAD

**Issue by sagi-t** [dounokouno/TransmitMail#88]
いつもお世話になっております。

この度サーバーのPHPのバージョンを7.2から7.4に変更したところ
フォームを送信しようとすると「CSRFトークンが無効です」と
エラーが出るようになりました。
こちらの解消方法はありますでしょうか？

7.2に戻すと解消されることと、元から7.4を使っているサーバーなら
問題なく動作することを確認できています。

よろしくお願いいたします。

**Comment by sagi-t** [comment]
度々失礼いたします。
先の質問の件ですが、元から7.4を使っているサーバーにすべてのフォームを移転することになりましたので、取り下げさせていただきます。
既にお手を煩わせておりましたら申し訳ありませんでした。

今後もこちらのメールフォームを活用させていただきたく思います。
よろしくお願いいたします。

**Comment by dounokouno** [comment]
すみません、 issue が作られていたことに全く気づいていませんでしたmm 問題は解消されたようですので、 issue は close しておきますね。

ちなみに、今、パッと思いつく原因としては、 php.ini などで設定されている PHP の設定の差異でしょうか。 CSRF 対策機能には session を利用しているので、 session 周りの PHP の設定が何らかの理由で「7.2から7.4に変更したサーバー」と「元から7.4を利用しているサーバー」で差異があったのかもしれません。通常、マイナーバージョンが同じであれば PHP の設定は同じになる気がしますが、サーバー管理側が何らかの理由で「古いサーバー」と「新しいサーバー」、または「7.4の利用を開始したタイミング」の PHP の設定の初期値を変更したのかもしれません。あくまで想像ですけれども。ご参考までにmm
