### ISSUE TITLE
TransmitMail 2 で入力内容に応じて送信メールの宛先を切り替えたい

### ISSUE THREAD

**Issue by ts-mori** [dounokouno/TransmitMail#90]
dounokouno様
いつも大変お世話になっております。

https://qiita.com/dounokouno/items/21dcf87f2e43a73be551
を拝見し、カスタマイズはメアドだけでコピペしてみたのですが、
画面が真っ白で、うまく行きませんでした。

５年以上前の記事なので、仕様等変わっていますでしょうか？

2回に分けられているので間違っているかもしれないので、
lib/exTransmitMail.phpは以下で大丈夫でしょうか？
```
<?php
class exTransmitMail extends TransmitMail
{
}
/**
 * メール送信の前の処理
 */
public function afterSetTemplateProperty()
{
    if ($this->page_name === 'finish') {
        switch ($this->post['お問い合わせ内容']) {
            case '利用方法について':
                $this->config['to_email'] = $this->config['to_email_support'];
                break;
            case '資料請求':
                $this->config['to_email'] = $this->config['to_email_material'];
                break;
            case 'その他':
            default:
                // 「その他」または選択がない場合は to_email 宛にメールを送信するので、ここでは特に何もしない
                break;
        }
    }
}
```
phpのバージョンは7.4です
どうぞよろしくお願いいたします。

**Comment by ts-mori** [comment]
dounokouno様
いつも大変お世話になっております。
https://github.com/dounokouno/TransmitMail/tree/example_branch_of_email

くだんのページのgitを見つけメールアドレスだけ変えて、サーバーにそのままUPしました。
確認ページで送信ボタンは押せるものの、送信できない状態で真っ白になります。

エラーログは
[21-Feb-2023 15:49:57 Asia/Tokyo] PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /httpd/contact/lib/qdmail.php on line 661
となります。

エラーは何をすればなくなりますでしょうか？
どうぞよろしくお願いいたします。

**Comment by dounokouno** [comment]
qdmail.php でエラーが出ているんですね。。時間を見つけて確認してみますね。（お返事が遅くなったらすみませんmm）

**Comment by dounokouno** [comment]
もしかすると TransmitMail のバージョンが古いかもしれません。ご利用の TransmitMail のバージョンはいくつかご確認をお願いいたします。

**Comment by ts-mori** [comment]
当時のgitによると
\contact\lib\TransmitMail.php
https://github.com/dounokouno/TransmitMail/tree/example_branch_of_email
    const VERSION = '2.0.0';
となります。
ただ最新const VERSION = '2.6.2';
だと、確認画面に行かず送信画面で、真っ白になります。
よろしくお願いいたします。

**Comment by dounokouno** [comment]
最後までサポートできずすみませんでした🙇
