### ISSUE TITLE
SMTPパスワードを保護する方法。

### ISSUE THREAD

**Issue by sn0wm1ku** [dounokouno/TransmitMail#98]
SMTPパスワードがconfigファイルに設置すれば、公開的になります。
`https://example.com/config/config.yml` にアクセスされます。

**Comment by dounokouno** [comment]
@sn0wm1ku 様

上記件はご指摘の通りではあるのですが、 TransmitMail 公開当初はウェブサーバーは Apache を想定しており、 `config/.htaccess` 似て `config/` ディレクトリ以下のファイルはアクセス不可に設定していますので、 Apache であれば `config/config.yml` にアクセスすることはできないかと思います。

Apache 以外のウェブサーバーの場合は、上記と同様に `config/` ディレクトリ以下へのアクセス拒否を行うか、 `config/config.yml` のパーミッションを `400` のように変更いただくことで対応可能かもしれません（未検証）。

もしよろしければ現在設置されている、または想定されているウェブサーバーの環境（ Apache や Nginx + php-fpm など）をご教示いただければ幸いです。

**Comment by sn0wm1ku** [comment]
想定するサーバー環境はlighttpd + fpmです。

**Comment by sn0wm1ku** [comment]
https://github.com/dounokouno/TransmitMail/issues/98#issuecomment-2333248867
php:alpine-fpmイメージ上にlighttpdで同じ方法もできます。
ありがとうございます。

**Comment by dounokouno** [comment]
@sn0wm1ku 様

> php:alpine-fpmイメージ上にlighttpdで同じ方法もできます。

上記は、

> `config/` ディレクトリ以下へのアクセス拒否を行う

上記の設定を lighttpd で行うことができる、という意味でしょうか？

その場合、よろしければどのように設定を書くか、コメントにて共有いただくことは可能でしょうか？（他の lighttpd を使う方の参考になるかと思いますので。）

**Comment by sn0wm1ku** [comment]
> @sn0wm1ku 様
> 
> > php:alpine-fpmイメージ上にlighttpdで同じ方法もできます。
> 
> 上記は、
> 
> > `config/` ディレクトリ以下へのアクセス拒否を行う
> 
> 上記の設定を lighttpd で行うことができる、という意味でしょうか？
> 
> その場合、よろしければどのように設定を書くか、コメントにて共有いただくことは可能でしょうか？（他の lighttpd を使う方の参考になるかと思いますので。）

.htaccessでconfig/ディレトリ以下のアクセス拒否を行うことです。
`lighttpd`　が　`.htacccess`　を使えそうです。
